apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: "innodb"
  namespace: demo
spec:
  version: "8.0.24"
  replicas: 3
  topology:
    mode: InnoDBCluster
    group:
      name: "dc002fc3-c412-4d18-b1d4-66c1fbfbbc9b"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  useAddressType: IP